### ISSUE TITLE
Add test for volume removal

### ISSUE THREAD

**Issue by cjellick** [rancherio/python-agent#14]
See this note:
https://github.com/rancherio/python-agent/blob/a833abbdd1a68bab9c97292593e92ecac9020edb/tests/test_docker.py#L484-L488

Testing isn't complete and self-contained for this feature. The crux of the issue is that any test that actually interacts with the file system will fail on Mac (when using b2d). After discussing with @ibuildthecloud , we decided that the best course of action is to write a test that will work in a native docker installation but fails when ran on a Mac via b2d.

**Comment by deniseschannon** [comment]
Moving issues into rancherio/rancher.

https://github.com/rancherio/rancher/issues/329
