### ISSUE TITLE
In b2d: can't find cadvisor files

### ISSUE THREAD

**Issue by cjellick** [rancherio/python-agent#16]
When running rancher agent inside of b2d, the agent fails to find the cadvisor and nsenter files, even though they appear to exist when you do an ls on their directory.

Steps to reproduce:
1. Run ```docker logs -f rancher-agent | grep cadvisor```. You should see:

> nsenter: failed to execute /var/lib/cattle/pyagent/cattle/plugins/cadvisor/cadvisor: No such file or directory

Actual result:
The agent cant find cadvisor

Expected result:
The agent should be able to find cadvisor and you should see this error message.

**Comment by ibuildthecloud** [comment]
Fixed by #44
