### ISSUE TITLE
tests/test_docker.py::test_instance_activate_devices failes with docker-py 0.7.1

### ISSUE THREAD

**Issue by hibooboo2** [rancherio/python-agent#47]

**Comment by hibooboo2** [comment]
============================= test session starts ==============================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 52 items

tests/test_docker.py .................F...............
tests/test_libvirt.py sssssssssss
tests/test_libvirt_storage.py ssssssss

=================================== FAILURES ===================================
________________________ test_instance_activate_devices ________________________

agent = <cattle.agent.Agent object at 0x1105aa990>
responses = <tests.response_holder.ResponseHolder instance at 0x11055c758>

    @if_docker
    def test_instance_activate_devices(agent, responses):
        _delete_container('/c861f990-4472-4fa1-960f-65171b544c28')
        input_devices = ['/dev/null:/dev/xnull', '/dev/random:/dev/xrandom:rw']
        expected_devices = {}
        for input_device in input_devices:
            parts_of_device = input_device.split(':')
            key = parts_of_device[0]
            expected_devices[key] = {
                "PathOnHost": parts_of_device[0],
                "PathInContainer": parts_of_device[1]
            }
            if len(parts_of_device) == 3:
                expected_devices[key]["CgroupPermissions"] = parts_of_device[2]
            else:
                expected_devices[key]["CgroupPermissions"] = "rwm"
    
        def pre(req):
            instance = req['data']['instanceHostMap']['instance']
            instance['data']['fields']['devices'] = input_devices
    
        def post(req, resp):
            docker_inspect = resp['data']['instance']['+data']['dockerInspect']
            actual_devices = docker_inspect['HostConfig']['Devices']
    
            assert len(expected_devices) == len(actual_devices)
    
            for act_dvc in actual_devices:
                exp_dvc = expected_devices[act_dvc['PathOnHost']]
                assert exp_dvc['PathOnHost'] == act_dvc['PathOnHost']
                assert exp_dvc['PathInContainer'] == act_dvc['PathInContainer']
                assert exp_dvc['CgroupPermissions'] == act_dvc['CgroupPermissions']
    
            container_field_test_boiler_plate(resp)
    
        schema = 'docker/instance_activate_fields'
>       event_test(agent, schema, pre_func=pre, post_func=post)

tests/test_docker.py:465: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/common_fixtures.py:76: in event_test
    resp = agent.execute(req)
cattle/agent/__init__.py:15: in execute
    return self._router.route(req)
cattle/plugins/core/event_router.py:13: in route
    resp = handler.execute(req)
cattle/agent/handler.py:33: in execute
    return method(req=req, **req.data.__dict__)
cattle/compute/__init__.py:19: in instance_activate
    action=lambda: self._do_instance_activate(instance, host, progress)
cattle/agent/handler.py:71: in _do
    action()
cattle/compute/__init__.py:19: in <lambda>
    action=lambda: self._do_instance_activate(instance, host, progress)
cattle/plugins/docker/compute.py:312: in _do_instance_activate
    c.start(container['Id'], **start_config)
venv/lib/python2.7/site-packages/docker_py-0.7.1-py2.7.egg/docker/client.py:952: in start
    self._raise_for_status(res)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <docker.client.Client object at 0x1105e8f10>, response = <Response [404]>
explanation = None

    def _raise_for_status(self, response, explanation=None):
        """Raises stored :class:`APIError`, if one occurred."""
        try:
            response.raise_for_status()
        except requests.exceptions.HTTPError as e:
>           raise errors.APIError(e, response, explanation=explanation)
E           APIError: 404 Client Error: Not Found ("Cannot start container 32c7e84b8ce2f62bb7b01a118f5fbb5f2bb3cc6aa2856cfe57268cb5c1caeb45: error gathering device information while adding custom device "/dev/null,/dev/xnull": lstat /dev/null,/dev/xnull: no such file or directory")

venv/lib/python2.7/site-packages/docker_py-0.7.1-py2.7.egg/docker/client.py:94: APIError
=============== 1 failed, 32 passed, 19 skipped in 42.29 seconds ===============

**Comment by ibuildthecloud** [comment]
@hibooboo2 is this fixed now?  Can you link to the PR?

**Comment by hibooboo2** [comment]
Yes it is fixed with this pr. https://github.com/rancherio/python-agent/pull/53
