### ISSUE TITLE
Include docker-py 0.7.2

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/python-agent#68]
Docker-py 0.7.2 has MacAddress support now.

ping @hibooboo2

**Comment by ibuildthecloud** [comment]
@hibooboo2 Let's get this in for next weeks release.

**Comment by hibooboo2** [comment]
#72 fixes this

**Comment by cloudnautique** [comment]
@hibooboo2 should this be closed?

**Comment by hibooboo2** [comment]
Yes
